## Scalar Value
scalor has 0 dimension

( ) = scaler vlues

In [19]:
import numpy as np
a: np.ndarray= np.array(1000) # object to store 
display(f"objet {a}") # prints of objects
display(f"object type with global function{type(a)}")
display(f"object shap {a.shape}")  # prints the shap of objects
display(f"object type  {a.dtype}")  # prints dtype of objects
display(f"Number of dimension {a.ndim}")  # prints  ndim of objects
display(f"Total items in array {a.size}")  # prints size of objects
display(a.itemsize)  # prints itemsize of objects

'objet 1000'

"object type with global function<class 'numpy.ndarray'>"

'object shap ()'

'object type  int32'

'Number of dimension 0'

'Total items in array 1'

4

## Vacter Type
vacter type have more than  0 dimension

([ 1,2,3]) = vector dimension

In [18]:
import numpy as np
a: np.ndarray= np.array([1,2,3,4]) # object to store 
display(f"objet {a}") # prints of objects
display(f"object type with global function{type(a)}")
display(f"object shap {a.shape}")  # prints the shap of objects
display(f"object type  {a.dtype}")  # prints dtype of objects
display(f"Number of dimension {a.ndim}")  # prints  ndim of objects
display(f"Total items in array  {a.size}")  # prints size of objects
display(a.itemsize)  # prints itemsize of objects

'objet [1 2 3 4]'

"object type with global function<class 'numpy.ndarray'>"

'object shap (4,)'

'object type  int32'

'Number of dimension 1'

'Total items in array \n 4'

4

## Matrix Type


In [21]:
import numpy as np
data= [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
a: np.ndarray= np.array(data) # object to store 
display(f"objet {a}") # prints of objects
display(f"object type with global function{type(a)}")
display(f"object shap {a.shape}")  # prints the shap of objects
display(f"object type  {a.dtype}")  # prints dtype of objects
display(f"Number of dimension {a.ndim}")  # prints  ndim of objects
display(f"Total items in array  {a.size}")  # prints size of objects
display(a.itemsize)  # prints itemsize of objects

'objet [[ 1  2  3  4]\n [ 5  6  7  8]\n [ 9 10 11 12]]'

"object type with global function<class 'numpy.ndarray'>"

'object shap (3, 4)'

'object type  int32'

'Number of dimension 2'

'Total items in array  12'

4

# Numpy with NDArray typing suport

In [23]:
from nptyping import NDArray, Shape,UInt64
from typing import Any

data:NDArray[Shape["10"], Any]= np.arange(1,11)
print(data)

[ 1  2  3  4  5  6  7  8  9 10]


In [25]:

data:NDArray[Shape["10"], Any]= np.arange(1,11)
print(data)
print(data+5) # add 5 to each elent of numpy array

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]


In [29]:
data:list[int]=list(range(1,11))
print(data)
[i+5 for i in data ] # adding 5 in each elent of simple list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

## numpy advance operation vs List operation

In [32]:
data:list[int] = list(range(1,21))
print(data)

print(data[5:11]) # slicing 
data[5:11]=100 # normal python list do not allow to apdate the list


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


TypeError: can only assign an iterable

In [35]:
nData:NDArray[Shape["20"],Any]= np.arange(1,21)
print(nData)
print(nData[5:11])
nData[5:11]=100 ## numpy list can be updated
print(nData)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[  1   2   3   4   5 100 100 100 100 100 100  12  13  14  15  16  17  18
  19  20]


## Numpy 1 dimension Function

In [100]:
state_bank:NDArray[Shape["10"],Any]= np.array([1,7,8,10])
print(state_bank) # it will print 4 integer num
state_bank % 2==0 # it will convert num into boolen (true false)
print(state_bank % 2==0)

[ 1  7  8 10]
[False False  True  True]


In [41]:
state_bank:NDArray[Shape["10"],Any]= np.array([1,7,8,10])
state_bank[state_bank % 2==0]#it will match num and boolean and retun that value that have true num


array([ 8, 10])

In [43]:
# here we want get intersectiun of state_bank and  ubl_bank 
state_bank:NDArray[Shape["10"],Any]= np.array([1,7,8,10])

#generate the random 20 number between 1 to 100
ubl_bank:NDArray[Shape["10"],Any] = np.random.randint(1,100,20)

display(state_bank)
display(ubl_bank)

array([ 1,  7,  8, 10])

array([50,  1, 55, 55, 38, 25, 80, 35, 47, 52, 71, 91, 62, 32, 51, 26,  7,
       26, 60, 44])

In [44]:
display(state_bank)
display(ubl_bank)
#        4 item  search from 20
np.in1d(state_bank, ubl_bank) # first variable (state_bank) items length return with bolean

array([ 1,  7,  8, 10])

array([50,  1, 55, 55, 38, 25, 80, 35, 47, 52, 71, 91, 62, 32, 51, 26,  7,
       26, 60, 44])

array([ True,  True, False, False])

In [45]:
display(state_bank)
display(ubl_bank)
#    
state_bank[np.in1d(state_bank, ubl_bank)] #only retun true matched value

array([ 1,  7,  8, 10])

array([50,  1, 55, 55, 38, 25, 80, 35, 47, 52, 71, 91, 62, 32, 51, 26,  7,
       26, 60, 44])

array([1, 7])

In [50]:
np.intersect1d(state_bank,ubl_bank) 

array([1, 7])

In [49]:
x:NDArray[Shape["10"],Any] = np.array([2,4,6,8,9])
y:NDArray[Shape["10"],Any] = np.array([2,3,7,9,3])
display(x)
display(y)

np.where(x>y,x,y) # it will return greater number that either from x or from y

array([2, 4, 6, 8, 9])

array([2, 3, 7, 9, 3])

array([2, 3, 6, 8, 3])

In [51]:
x:NDArray[Shape["10"],Any] = np.array([2,4,6,8,9])
y:NDArray[Shape["10"],Any] = np.array([2,3,7,9,3])
display(x)
display(y)

np.where(x <y,x,y) # it will return smaller number that either from x or from y

array([2, 4, 6, 8, 9])

array([2, 3, 7, 9, 3])

array([2, 3, 6, 8, 3])

##  Create Numpy Array

In [57]:
# 2 dimention array
a:NDArray[Shape["Size, Size"],Any]=np.array([[1,2,3],
                                             [4,5,6],
                                             [7,8,9]])

print(a)

a:NDArray[Shape["Size, Size"],Any]=np.array([[1,2,3],
                                             [4,5,6],
                                             ])

print("\n",a)
a:NDArray[Shape["Size, Size"],Any]=np.array([[1,2],
                                             [4,5],
                                            ])

print("\n",a)

a:NDArray[Shape["Size, Size"],Any]=np.array([["a"],
                                             ["b"],
                                            ])

print("\n",a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[1 2 3]
 [4 5 6]]

 [[1 2]
 [4 5]]

 [['a']
 ['b']]


In [101]:
# 2 dimention array
a:NDArray[Shape["*, *"],Any]=np.array([[1,2,3],
                                             [4,5,6],
                                             [7,8,9]])

print(a)

a:NDArray[Shape["*, *"],Any]=np.array([[1,2,3],
                                             [4,5,6],
                                             ])

print("\n",a)
a:NDArray[Shape["*, *"],Any]=np.array([[1,2],
                                             [4,5],
                                            ])

print("\n",a)

a:NDArray[Shape["*, *"],Any]=np.array([["a"],
                                             ["b"],
                                            ])

print("\n",a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[1 2 3]
 [4 5 6]]

 [[1 2]
 [4 5]]

 [['a']
 ['b']]


In [59]:
np.who()

Name            Shape            Bytes            Type

_               5                20               int32
__              2                8                int32
___             5                20               int32
a               2 x 1            8                str32
nData           20               80               int32
sata_bank       4                16               int32
ubl_bank        20               80               int32
state_bank      4                16               int32
_39             4                4                bool
_41             2                8                int32
_44             4                4                bool
_45             2                8                int32
_46             2                8                int32
x               5                20               int32
y               5                20               int32
_47             5                20               int32
_48             5                20               

In [60]:
# 1 dimension array
a:NDArray[Shape["Size"],Any]= np.arange(1,11)
print(a)

a:NDArray[Shape["Size"],Any]= np.arange(1,7)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 6]


In [71]:
# 2 dimension array
b:NDArray[Shape["Size,Size"],Any]= np.arange(3*3).reshape(3,3) # rows X column
print(b)

a:NDArray[Shape["Size, Size"],Any]= np.arange(4*3).reshape(4,3)
print("\n",a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [75]:
# 3 dimension array
b:NDArray[Shape["Size,Size,Size"],Any]= np.arange(2*3*3).reshape(2,3,3) # rows X column
print(b)
print("===============")
a:NDArray[Shape["Size,Size,Size"],Any]= np.arange(5*2*2).reshape(5,2,2)
print("\n",a)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]

 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [77]:
np.asarray([1,2,3,4])

array([1, 2, 3, 4])

In [80]:
a=np.zeros(5)
print(a)
b=np.zeros((3,2)) # with two dimension array
print("\n",b)


[0. 0. 0. 0. 0.]

 [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [83]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [84]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [87]:
a:NDArray[Shape["Size,Size,Size"],Any]= np.arange(2*2).reshape(2,2)
print(a)
print("============")
b=np.ones_like(a) # it will generate cop of a and replace all element in 1
print(b)

[[0 1]
 [2 3]]
[[1 1]
 [1 1]]


In [92]:
b:NDArray[Shape["Size,Size,Size"],Any]= np.arange(4*2*3).reshape(4,2,3) # rows X column
print(b)
print("===========")
#slicing on 3 simension
b[[0,-1],::,::]  # it will return first 0 and last -1 picture from 4 pitcher

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[18, 19, 20],
        [21, 22, 23]]])

# function

In [99]:
data:NDArray[Shape["10"], Any]= np.arange(1,11)
print(data)
print(data.max())
print(data.min())
print(data.mean())
print(data.std())
print(data.sum())
print(data.cumsum())
print(data.argmax())
print(data.argmin())

[ 1  2  3  4  5  6  7  8  9 10]
10
1
5.5
2.8722813232690143
55
[ 1  3  6 10 15 21 28 36 45 55]
9
0
